### ISSUE TITLE
Is rejuvenate dead? Does rejuvenate need to be rejuvenated?

### ISSUE THREAD

**Issue by mcarans** [rejuvenate/rejuvenate#11]
I notice a number of issues with no replies. Is this project still alive? Is it possible to rejuvenate other projects?

**Comment by ThomDietrich** [comment]
Hey @mcarans,
yes we need to!! Would you like to join the group to help with that?

**Comment by mcarans** [comment]
@ThomDietrich thanks for your reply. In the end, myself and some others forked the project we wanted to revive (flakehell) and renamed it [flakeheaven](https://github.com/flakeheaven/flakeheaven). Unfortunately, I don't have extra capacity after helping out with flakeheaven to help with this project as well. I'll close this issue, since you've indicated that rejuvenate will be kept alive.

**Comment by ThomDietrich** [comment]
Looks really good! Congrats!
Sorry we didn't jump in in-time. If you ever want to rejuvenate another project, consider to post here again and we will gladly help!
