### ISSUE TITLE
Please revive History Explorer Card

### ISSUE THREAD

**Issue by erkr** [rejuvenate/rejuvenate#14]
The [History Explorer Card](https://github.com/alexarch21/history-explorer-card) for home assistant in HACS was declared EOL by the Author.
As it is a great asset for the home assistant community, it would be great if it was rejuvenated 😊

**Comment by ThomDietrich** [comment]
More context: https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978

Hello @erkr, would you be willing to take the lead and did you already find likeminded developers to pick up the work? A rejuvenate fork is a nice idea but won't be worth much if we can't establish an active community.

Cheers!

**Comment by erkr** [comment]
@ThomDietrich 
I don't have the knowledge for programming the card, but I can moderate and test myself. I agree we need enthousiast programmers interested to help out. 
Is it ok to poll this on the link you provided?

**Comment by ThomDietrich** [comment]
Yes no better place than there. Ask around and you might find a couple of interested people.

The focus should be to find people interested to continue development, but it would already be a great step to find a group willing to moderate the project. This way outside contributors can still offer their individual Pull Requests with bug fixes and feature additions - something that would stay unanswered in the upstream repo.

**Comment by erkr** [comment]
I will do a poll then, thanks!

Update: no responses (yet)

**Comment by erkr** [comment]
@ThomDietrich 
Thanks for your guidance. There are no responses, so I guess this won't fly, and I will close this request

**Comment by SpangleLabs** [comment]
Darn, I only just found this. (I rarely read HA forum)
I use that card extensively, and really love it, and have a list of tweaks I would love to make and I'm eager to contribute to it!
I've not done much HA lovelace stuff before, but I've been digging through HA code lately and I've got decent JS experience.

I'm not sure the process here, or whether I should just fork the repo myself? (Or whether there's an alternative card or fork of that card which I should just switch to)

**Comment by erkr** [comment]
That is fully up to you, just fork and find at least one or more others to join is a good start. 
Count me in to test 😉

**Comment by SpangleLabs** [comment]
I made a fork, over here: https://github.com/SpangleLabs/history-explorer-card
And created a couple issues there for things I wanted to see, especially a full reference of all configuration, which I've started working on in a branch.

Though I'm a bit worried about the lack of any instructions on how to build the project, or what versions of dependencies were used:
https://github.com/SpangleLabs/history-explorer-card/issues/3

**Comment by alexarch21** [comment]
I uploaded the HEC dependencies here, if anyone wants to continue development of this card. Would be nice if it wouldn't die I guess.

https://github.com/alexarch21/hec_dependencies

**Comment by erkr** [comment]
I'm close this issue. Hopefully we get more contributors
