### ISSUE TITLE
Create fork of stickeeuk/grumphp-tasks

### ISSUE THREAD

**Issue by deevus** [rejuvenate/rejuvenate#4]
Link: https://github.com/stickeeuk/grumphp-tasks
PR 1: https://github.com/stickeeuk/grumphp-tasks/pull/3
PR 2: https://github.com/stickeeuk/grumphp-tasks/pull/4

**Comment by deevus** [comment]
Possibily rename it to `grumphp-eslint` since it doesn't have any other purpose.

**Comment by Mezzle** [comment]
hey - I originally created this, but have since left the company.

More than happy to accept contributions for this on my fork:-

https://github.com/mezzle/grumphp-tasks

**Comment by Mezzle** [comment]
I've also integrated these changes.

**Comment by TPS** [comment]
@deevus Since @Mezzle is continuing development, I suppose this doesn't need a `rejuvenate` fork, correct?  Let us know!

**Comment by deevus** [comment]
Looks like it. Thanks!
