### ISSUE TITLE
Let's rejuvenate react-custom-scrollbars

### ISSUE THREAD

**Issue by Tomassito** [rejuvenate/rejuvenate#6]
https://github.com/malte-wessel/react-custom-scrollbars
Seems to be dead for a long time now despite some active interest from the community to become co-maintainers:
https://github.com/malte-wessel/react-custom-scrollbars/issues/275

**Comment by TPS** [comment]
I've put a call for maintainers @ https://github.com/malte-wessel/react-custom-scrollbars/issues/275#issuecomment-561377616.  Pending responses, I'll open a fork w/ those folks setup.

**Comment by TPS** [comment]
It's been several days, & there's been only 2 positive responses to my request for maintainers.  I'll wait a few more days yet, then decide whether to fork or close this request `won't fix`/`invalid` ifF there continues to be uncertain interest.

**Comment by TPS** [comment]
This looks to be fulfilled sufficiently via https://github.com/sakhnyuk/rc-scrollbars.  If so, I'll close this in favor of development there.
